import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
if(typeof global === 'undefined'){var global = window;}
if(typeof Buffer === 'undefined'){var Buffer = require('buffer').Buffer;}
if(typeof process === 'undefined'){var process = require('process');}
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "node-pty",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js"
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
